# Remove all files that are not supposed to be in the repo.
# They are generated by autogen.sh

rm -f Makefile Makefile.in configure aclocal.m4
rm -f config.h.in config.guess config.sub install-sh
rm -f ltconfig ltmain.sh missing mkinstalldirs stamp-h.in missing
