#!/bin/sh
exec guile -s $0 $*
!#
(define defmacro
  (let ((defmacro-transformer
	  (lambda (name parms . body)
	      `(define ,name
	    (let ((transformer (lambda ,parms ,@body)))
		 ((lambda (transformer)
		     (defmacro:transformer transformer))
		  transformer))))))
    (defmacro:transformer defmacro-transformer)))

(if (null? (cdr (command-line)))
    (map display (list 
                  "Usage: "
                  (car (command-line))
                  " files-to-compile-ending-with.scm\n"))
    (begin
      (debug-disable 'debug)
      (load-user-init)
      (require 'hobbit)
      (apply hobbit (cdr (command-line)))))