#! /bin/sh -x
# Usage: checkout-hack
#        checkout-hack -a       # "all" includes branches
#
# Env var: CVSROOT

CVSROOT=${CVSROOT-':pserver:anoncvs@subversions.gnu.org:/cvsroot/guile'}
export CVSROOT

branches="1-4 1-6"

cvs co hack

if [ x"$1" = x-a ] ; then
    cd hack
    for branch in $branches ; do
        cvs co -d core-$branch -r branch_release-$branch core
    done
fi

# checkout-hack ends here
