#! /bin/sh -x
# Usage: checkout-hack

CVSROOT=${CVSROOT-':pserver:anoncvs@subversions.gnu.org:/cvsroot/guile'}
export CVSROOT

branches="1-4 1-6"

cvs co hack
cd hack
for branch in $branches ; do
    cvs co -d core-$branch -r branch_release-$branch core
done

# checkout-hack ends here
