#!/bin/sh -x
# usage: dist-guile-www [part1 | part2]

set -e

part1 ()
{
rm -rf tmp
mkdir -p tmp/tmp/tmp
cd tmp/tmp/tmp
checkout-guile-cvs-module guile-www
cd guile-www
./autogen.sh
rm -rf /tmp/a/b/c
./configure --prefix=/tmp/a/b/c
make
make dist
version=`awk '/AM_INIT_AUTOMAKE/ {print $2}' configure.in | sed 's/,//g'`
mkdir tmp
cd tmp
tar xzf ../guile-www-${version}.tar.gz
cd guile-www-${version}
./configure --prefix=/tmp/a/b/c
make
make install
ls -lR /tmp/a/b/c
:
: part1 done
:
}

part2 ()
{
rm -rf /tmp/a/b/c
test -d tmp/tmp/tmp/guile-www/
mv tmp/tmp/tmp/guile-www/guile-www-*.tar.gz .
rm -r tmp
:
: part2 done
:
}

usage ()
{
echo usage: $0 '[part1 | part2]'
echo '(part1 stops after doing an install in /tmp/a/b/c ...'
echo 'look that over and it'\''s ok, do part2 (where you did part1) ...'
echo 'part2 moves the new tarball to . and removes ./tmp and /tmp/a/b/c)'
}

case x"$1" in xpart[12]) $1 ; exit $? ;; *) usage ; exit 1 ;; esac

# dist-guile-www ends here
