scripts =					\
	checkout-guile-cvs-module		\
	nightly					\
	update-anon-cvs-public			\
	dist-guile-www				\
	update-anon-cvs

# Yes, sometimes people will check in files w/o +x -- that's life.

all:
	chmod +x $(scripts)
