#!/bin/sh

script_dir="$1"
[ -d "${script_dir}" ] || {
  echo "$0: bad script directory: ${script_dir}" >&2
  exit 1
}

cd ${script_dir}

### Copy our latest repository files over to the public CVS server.
###
### See the comments atop update-anon-cvs for exactly what these
### environment variables are supposed to mean.

CVSROOT_PATH=/u/src/master
PUBLISHED_SUBDIRS=guile-comp guile-core guile-doc guile-rgx-ctax \
  guile-scsh guile-tcltk guile-tk guile-www
PUBLIC_SERVER=egcs.cygnus.com
PUBLIC_CVSROOT_PATH=/egcs/carton/cvsfiles/guile

./update-anon-cvs
