#!/bin/sh
# Usage: render-bugs [BUGS-DB-DIR]
# Display the headers of the bug files in ../workbook/bugs/
# (or BUGS-DB-DIR if specified).

cd ${1-../workbook/bugs/}
find . -name '[a-z0-9]*' -type f \
    \( -printf "name: %f\n" \
       -exec sed '/^$/ q' '{}' \; \) \
    -maxdepth 1

# render-bugs ends here
