#!/bin/bash
#### update-anon-cvs-public --- public (remote) half of update-anon-cvs
#### Jim Blandy <jimb@red-bean.com> --- July 1998

#### Usage: update-anon-cvs-public PUBLIC_CVSROOT_PATH
####
#### This script is meant to execute on the public CVS server machine,
#### recieve the files from the private machine, unpack them, and move
#### them into place in some atomic way.
####
#### PUBLIC_CVSROOT_PATH is the directory on this machine to unpack the
#### repository files into.
####
#### This script receives a gzipped tar file on its standard input.

hostname="`hostname`"
progname="`basename $0`"
public="$1"

#### Some sanity checks.

test -d ${public} || {
  echo -n "${progname}: not a directory: ${hostname}:${public}" >&2
  exit 1
}

test -w ${public} || {
  echo -n "${progname}: directory not writable: ${hostname}:${public}" >&2
  exit 1
}

cd ${public}


## Pick out the name of the old directory (or directories) which
## we'll delete once we've successfully transferred the new files
## over.
old="$(ls -d snapshot-* 2>/dev/null)"

## Pick a new directory name.
new="snapshot-$(date +%s)-$$"

## Receive the files from the private end.
mkdir $new
(
  cd $new
  gunzip | tar xf - || exit $?
) || exit $?

## Set the permissions on the new directories properly.
find $new -type d | xargs chmod g+sw
chgrp -R anoncvs $new

## Move the symlink from the old directory to the new directory.
ln --symbolic --force --no-dereference $new ./current

## Wait a little bit to allow anyone using the old files to finish,
## and then delete the old tree(s).
(
  sleep 10
  rm -rf $old
) &

## Clean up the script file.
rm public || exit $?

exit 0
