#!/usr/local/bin/bash
#### update-anon-cvs --- update the public anonymous CVS repository for Guile
#### Jim Blandy <jimb@red-bean.com> --- July 1998

#### Copy a set of subdirectories from a CVS repository on one machine
#### to a repository on another, and switch between them as atomically
#### as possible.
####
#### The procedure:
#### - Make a tar file of the appropriate directories from a local repository.
#### - unpack that tar file in a subdirectory of the public repository.
#### - Switch a symlink over from the old subdirectory to the new subdirectory.
#### - Delete the old subdirectory.

#### Parameters:

#### PRIVATE_CVSROOT_PATH - the name of the parent directory in the
####   private CVS repository containing the directories we want to
####   copy over to the public CVS repository.
#### PUBLISHED_SUBDIRS - list of subdirectories of PRIVATE_CVSROOT_PATH
####   that should be copied.  Space-delimited.
#### PUBLIC_SERVER - name of the machine containing the public repository.
####   Note that this isn't necessarily the public CVS server; they might
####   share the repository via NFS.
#### PUBLIC_CVSROOT_PATH - name of the parent directory on the public CVS
####   server; the symlink, and the directories it points at, live here.

progname="`basename $0`"

private="${PRIVATE_CVSROOT_PATH}"
server="${PUBLIC_SERVER}"
public="${PUBLIC_CVSROOT_PATH}"

#### Some sanity checking:

[ -d "${private}" ] || {
  echo "${progname}: PRIVATE_CVSROOT_PATH is not a directory: ${private}" >&2
  exit 1
}

for subdir in ${PUBLISHED_SUBDIRS}; do
  [ -d "${private}/${subdir}" ] || {
    echo -n "${progname}: published directory does not exist: " >&2
    echo "${private}/${subdir}" >&2
    exit 1
  }
done

ssh ${server} true || {
  echo "${progname}: could not connect to ${server} via ssh" >&2
  exit 1
}


#### Transfer over the script for the public side.
scp update-anon-cvs-public "${server}:${public}/public" || exit $?

#### Tar up the source directories and send them across.
(
  cd ${private}
  tar cvf - ${PUBLISHED_SUBDIRS} \
  | gzip --best
) \
| ssh -o 'Compression yes' -o 'CompressionLevel 6' ${server} \
    "${public}/public ${PUBLIC_CVSROOT_PATH}" || exit $?

exit 0
