% Original attribution:

%
% STk Reference manual (Appendix: An Introdution to STklos)
%
%           Author: Erick Gallesio [eg@unice.fr]
%    Creation date: 22-May-1994 22:13
% Last file update: 22-Apr-1998 11:04
%

% Adapted for use in Guile with the authors permission

\input texinfo   @c -*-texinfo-*-
@c %**start of header
@paragraphindent 0pt
@setfilename goops.info
@settitle Goops Manual
@setchapternewpage odd
@c %**end of header

@ifinfo
This file documents goops, an Object Oriented extension for Guile.

Copyright 1998 Erick Gallesio

Permission is granted to ...
@end ifinfo

@c  This title page illustrates only one of the
@c  two methods of forming a title page.

@titlepage
@title Goops Manual
@author Erick Gallesio

@c  The following two commands
@c  start the copyright page.
@page
@vskip 0pt plus 1filll
Copyright @copyright{} 1998 Erick Gallesio

Published by GoopsBumps Publishing

Permission is granted to ...
@end titlepage

@node Top, Tutorial, (dir), (dir)

@ifinfo
This document describes ...

This document applies to version ...
of the program named ...
@end ifinfo

@menu
* Tutorial::                    
* Reference Manual::            
* MOP specification::           
* Index::                       
* Concept Index::               
* Function and Variable Index::  
@end menu

@node Tutorial, Reference Manual, Top, Top
@chapter Tutorial
@include goops-tutorial.texi

@node Reference Manual, MOP specification, Tutorial, Top
@chapter Reference Manual
[TO BE WRITTEN]

@node MOP specification, Index, Reference Manual, Top
@chapter MOP specification
[TO BE WRITTEN]

@node Index, Concept Index, MOP specification, Top
@chapter Index
@page
@node     Concept Index, Function and Variable Index, Index, Top
@unnumberedsec Concept Index

@printindex cp

@node Function and Variable Index,  , Concept Index, Top
@unnumberedsec Function and Variable Index

@printindex fn

@summarycontents
@contents
@bye
