\input texinfo
@c -*-texinfo-*-
@c %**start of header
@setfilename goops.info
@settitle Goops Manual
@setchapternewpage odd
@paragraphindent 0
@c %**end of header

@dircategory Scheme Programming
@direntry
* goops: (goops).          The GOOPS reference manual.
@end direntry

@ifinfo
This file documents GOOPS, an object oriented extension for Guile.

Copyright (C) 1999 Free Software Foundation

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

@end ifinfo

@c  This title page illustrates only one of the
@c  two methods of forming a title page.

@titlepage
@title Goops Manual
@author Christian Lynbech

@c  The following two commands
@c  start the copyright page.
@page
@vskip 0pt plus 1filll
Copyright @copyright{} 1999 Free Software Foundation

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

@end titlepage

@node Top, Getting Started, (dir), (dir)

@menu
* Getting Started::
* Reference Manual::            
* MOP specification::           
* Tutorial::                    
* Index::                       
* Concept Index::               
* Function and Variable Index::  
@end menu

@node Getting Started, Reference Manual, Top, Top

@node Reference Manual, MOP specification, Getting Started, Top
@chapter Reference Manual
[TO BE WRITTEN]

@node MOP specification, Tutorial, Reference Manual, Top
@chapter MOP specification
[TO BE WRITTEN]

@node Tutorial, Index, MOP specification, Top
@chapter Tutorial
@include goops-tutorial.texi

@node Index, Concept Index, Tutorial, Top
@chapter Index
@page
@node     Concept Index, Function and Variable Index, Index, Top
@unnumberedsec Concept Index

@printindex cp

@node Function and Variable Index,  , Concept Index, Top
@unnumberedsec Function and Variable Index

@printindex fn

@summarycontents
@contents
@bye
