QS_DIR=$(shell cd ..;pwd)
QS_LIB=$(QS_DIR)/libqs.so
GMP_LIB=$(QS_DIR)/gmp-2.0.2/libgmp.a
FFCALL_LIB=$(QS_DIR)/ffcall-1.5/avcall/libavcall.a
CC = gcc
CFLAGS=-g -O -DQSCHEME -I.. -I../gmp-2.0.2 -I../ffcall-1.5/avcall `gtk-config --cflags`

ifeq ($(shell which glade-config),)
GDEP := sglade.so
else
GDEP := 
endif


LIBGLADE=`libglade-config --libs`
#LIBGLADE=/usr/local/lib/libglade.so.0.2.4

GTKSRC=/usr/local/src/gtk+-1.2.7

all: sgtk gtkdefs.so gdkdefs.so $(GDEP)

ggtk: $(QS_LIB) sgtk_main.o ggtk.so
	$(CC) -o $@ $(CFLAGS) sgtk_main.o ggtk.so \
	`gtk-config --libs` $(QS_LIB) $(GMP_LIB) $(FFCALL_LIB)

ggtk.so : $(QS_LIB) ggtk.c
	$(CC) -o $@ -shared -fPIC $(CFLAGS) -DQSCHEME ggtk.c `gtk-config --libs`

sgtk: $(QS_LIB) sgtk_main.o sgtk.so gdkdefs.scm gtkdefs.scm \
	sgtk-typep.c sgtk-typep.i
	$(CC) -o $@ $(CFLAGS) sgtk_main.o sgtk.so \
	`gtk-config --libs` $(LIBGLADE) \
	$(QS_LIB) $(GMP_LIB) $(FFCALL_LIB)

sgtk.so : sgtk.c
	$(CC) -o $@ -shared -fPIC $(CFLAGS) sgtk.c `gtk-config --libs`

gdkdefs.scm: make-gtk-proto gtk.defs
	@echo "Generating $@"
	@perl make-gtk-proto $(GTKSRC)/gdk/gdk*.c > $@

gtkdefs.scm: make-gtk-proto gtk.defs
	@echo "Generating $@"
	@perl make-gtk-proto $(GTKSRC)/gtk/gtk*.c > $@

gtkdefs.so: gtkdefs.c
	$(CC) -o $@ -shared -fPIC $(CFLAGS) gtkdefs.c `gtk-config --libs`

gtkdefs.c: make-gtk-proto gtk.defs
	@echo "Generating $@"
	@perl make-gtk-proto --lang=c --dump-incomplete --modname=gtkdefs $(GTKSRC)/gtk/gtk*.c > $@

gdkdefs.so: gdkdefs.c
	$(CC) -o $@ -shared -fPIC $(CFLAGS) gdkdefs.c `gtk-config --libs`

gdkdefs.c: make-gtk-proto gtk.defs
	@echo "Generating $@"
	@perl make-gtk-proto --lang=c --dump-incomplete --modname=gdkdefs $(GTKSRC)/gdk/gdk*.c > $@

sglade.so: sglade.c
	$(CC) -o $@ -shared -fPIC $(CFLAGS) sglade.c $(LIBGLADE) `gtk-config --libs`

gtk.defs: 
	(cd $(GTKSRC)/gtk && \
	 perl makeenums.pl defs *.h ../gdk/gdktypes.h ../gdk/gdkrgb.h ) > gtk.defs

sgtk-typep.c: make-wrapper
sgtk-typep.i: make-wrapper
	perl -w make-wrapper $(GTKSRC)/gtk/gtk*.h

sgtk.defs: ../h2scm
	@echo "Generating sgtk.defs"
	@echo '(define *lib* "")' > sgtk.defs
	@../h2scm /usr/local/include/gtk/gtk.h 2>/dev/null | \
		grep -v va_end >> sgtk.defs

helloworld: helloworld.c 
	$(CC) `gtk-config --cflags`  $(CFLAGS) helloworld.c -o helloworld `gtk-config --libs`

clean: 
	rm -f *.o *.so sgtk ggtk helloworld
