SOBJ sgtk_is_accel_label(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_ACCEL_LABEL(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_adjustment(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_ADJUSTMENT(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_alignment(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_ALIGNMENT(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_arrow(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_ARROW(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_aspect_frame(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_ASPECT_FRAME(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_button_box(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_BUTTON_BOX(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_bin(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_BIN(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_box(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_BOX(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_button(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_BUTTON(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_calendar(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_CALENDAR(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_check_button(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_CHECK_BUTTON(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_check_menu_item(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_CHECK_MENU_ITEM(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_clist(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_CLIST(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_color_selection(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_COLOR_SELECTION(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_color_selection_dialog(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_COLOR_SELECTION_DIALOG(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_combo(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_COMBO(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_container(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_CONTAINER(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_ctree(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_CTREE(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_curve(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_CURVE(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_data(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_DATA(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_dialog(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_DIALOG(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_drawing_area(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_DRAWING_AREA(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_editable(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_EDITABLE(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_entry(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_ENTRY(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_event_box(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_EVENT_BOX(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_file_selection(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_FILE_SELECTION(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_fixed(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_FIXED(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_font_selection(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_FONT_SELECTION(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_font_selection_dialog(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_FONT_SELECTION_DIALOG(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_frame(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_FRAME(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_handle_box(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_HANDLE_BOX(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_hbutton_box(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_HBUTTON_BOX(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_hbox(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_HBOX(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_hpaned(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_HPANED(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_hruler(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_HRULER(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_hscale(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_HSCALE(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_hscrollbar(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_HSCROLLBAR(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_hseparator(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_HSEPARATOR(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_image(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_IMAGE(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_input_dialog(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_INPUT_DIALOG(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_item(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_ITEM(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_item_factory(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_ITEM_FACTORY(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_label(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_LABEL(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_layout(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_LAYOUT(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_list(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_LIST(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_list_item(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_LIST_ITEM(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_menu(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_MENU(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_menu_bar(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_MENU_BAR(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_menu_item(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_MENU_ITEM(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_menu_shell(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_MENU_SHELL(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_misc(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_MISC(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_notebook(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_NOTEBOOK(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_option_menu(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_OPTION_MENU(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_packer(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_PACKER(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_paned(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_PANED(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_pixmap(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_PIXMAP(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_plug(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_PLUG(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_preview(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_PREVIEW(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_progress(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_PROGRESS(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_progress_bar(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_PROGRESS_BAR(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_radio_button(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_RADIO_BUTTON(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_radio_menu_item(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_RADIO_MENU_ITEM(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_range(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_RANGE(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_ruler(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_RULER(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_scale(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_SCALE(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_scrollbar(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_SCROLLBAR(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_scrolled_window(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_SCROLLED_WINDOW(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_separator(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_SEPARATOR(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_socket(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_SOCKET(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_spin_button(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_SPIN_BUTTON(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_statusbar(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_STATUSBAR(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_table(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_TABLE(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_tearoff_menu_item(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_TEAROFF_MENU_ITEM(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_text(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_TEXT(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_tips_query(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_TIPS_QUERY(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_toggle_button(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_TOGGLE_BUTTON(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_toolbar(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_TOOLBAR(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_tooltips(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_TOOLTIPS(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_tree(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_TREE(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_tree_item(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_TREE_ITEM(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_vbutton_box(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_VBUTTON_BOX(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_vbox(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_VBOX(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_viewport(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_VIEWPORT(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_vpaned(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_VPANED(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_vruler(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_VRULER(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_vscale(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_VSCALE(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_vscrollbar(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_VSCROLLBAR(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_vseparator(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_VSEPARATOR(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_widget(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_WIDGET(SGTK_OBJECT(x)))); }
SOBJ sgtk_is_window(SOBJ x) { return(SCM_MKBOOL(SGTK_OBJECTP(x) && GTK_IS_WINDOW(SGTK_OBJECT(x)))); }
