@page
@node Binding Constructs
@chapter Binding Constructs

@c NJFIXME explain [env]
@c docstring begin (texi-doc-string "guile" "defined?")
@deffn primitive defined? sym [env]
Return @code{#t} if @var{sym} is defined in the top-level environment.
@end deffn


@c Local Variables:
@c TeX-master: "guile.texi"
@c End:
