@c Spell out this node fully, because it is the last real node
@c in the top-level menu.  Leaving off the pointers here causes
@c spurious makeinfo errors.
@node Type Index
@unnumbered Type Index

This is an alphabetical list of all the important data types defined in
the Gulie Programmers Manual.

@printindex tp
